apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-backend
  name: simple-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-backend
    spec:
      containers:
      - image: kebidge/simple-backend
        name: simple-backend
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_DATASOURCE_USERNAME
          value: kebidge
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://database:5432/simple-backend-db
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
status: {}