apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-frontend
  name: simple-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090
    name: http
  selector:
    app: simple-frontend
  type: LoadBalancer
status:
  loadBalancer: {}